import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const sidebar = {
    outer: {
      border: "solid 0.5px black",
      width: "100px",
      marginRight: "20px",
    },
    inner: {
      marginTop: "0px",
      marginRight: "0px",
      marginLeft: "0px",
    }
  }

  return (
    <html>
      <body>
        <div style={{ display: "flex" }}>
          <div style={sidebar.outer}>
            <div style={sidebar.inner}>
              <Link href="/">home</Link>
            </div>
            <div>
              <Link href="/mypage">mypage</Link>
            </div>
            <div>
              <Link href="/login">login</Link>
            </div>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
