import "./globals.css";
import HeaderComp from "./components/HeaderComp/HeaderComp";
import FooterComp from "./components/FooterComp/FooterComp";
import ContentsComp from "./components/ContentsComp/ContentsComp";

export const metadata = {
  title: "Free-Board",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html>
      <body>
        <HeaderComp />
        <ContentsComp children={children} />
        <FooterComp />
      </body>
    </html>
  );
}
